# Generated by Django 6.0.3 on 2026-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oficio', models.CharField(max_length=100, unique=True, verbose_name='Número de Oficio')),
                ('remitente', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=200)),
                ('asunto', models.CharField()),
                ('fecha_emision', models.DateField()),
                ('fecha_recepcion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
