# Generated by Django 6.0.3 on 2026-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='oficios_pdfs/'),
        ),
    ]
