# Generated by Django 6.0.3 on 2026-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oficio', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('remitente', models.CharField(max_length=200)),
                ('fecha_recepcion', models.DateField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='oficios_pdfs/')),
            ],
        ),
    ]
