# Generated by Django 6.0.3 on 2026-03-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_alter_oficio_numero_oficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.CharField(max_length=10, unique=True, verbose_name='ID de Área')),
                ('nombre', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='fecha_turnado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='instruccion',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucción de turno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='respuesta_pdf',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_pdfs/'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='area_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficios.area', verbose_name='Turnado a'),
        ),
    ]
