# Generated by Django 6.0.3 on 2026-03-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0003_area_oficio_fecha_respuesta_oficio_fecha_turnado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido en Ventanilla'), ('TURNADO', 'Turnado a Área'), ('EN_PROCESO', 'Asignado a Empleado'), ('FINALIZADO', 'Respondido / Archivado')], default='RECIBIDO', max_length=20),
        ),
        migrations.AddField(
            model_name='oficio',
            name='instruccion_interna',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucción de la Secretaría'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='area_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficios.area', verbose_name='Turnado a Área'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='instruccion',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucción de Turno'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('puesto', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='oficios.area')),
            ],
        ),
        migrations.AddField(
            model_name='oficio',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficios.empleado', verbose_name='Persona que resuelve'),
        ),
    ]
